--- #YAML:1.0
name:                     CPAN-Testers-Data-Uploads
version:                  0.20
abstract:                 CPAN Testers Uploads Database Generator
author:
  - Barbie <barbie@cpan.org>

license:                  artistic_2
distribution_type:        module
installdirs:              site

requires:
  perl:                           5.006
  Class::Accessor::Fast:          0
  CPAN::DistnameInfo:             0.10
  CPAN::Testers::Common::Article: 0
  CPAN::Testers::Common::DBUtils: 0
  Config::IniFiles:               0
  DBI:                            0
  DBD::mysql:                     0
  DBD::SQLite:                    0
  File::Basename:                 0
  File::Find::Rule:               0
  File::Path:                     0
  File::Slurp:                    0
  Getopt::Long:                   0
  IO::AtomicFile:                 0
  IO::File:                       0
  Net::NNTP:                      0
recommends:
  Test::CPAN::Meta:               0
  Test::CPAN::Meta::JSON:         0
  Test::Database:                 0
  Test::MockObject:               0
  Test::Pod:                      1.00
  Test::Pod::Coverage:            0.08
build_requires:
  Archive::Extract:               0
  Archive::Zip:                   0
  Test::More:                     0.70
  Test::Trap:                     0

provides:
  CPAN::Testers::Data::Uploads:
    file:     lib/CPAN/Testers/Data/Uploads.pm
    version:  0.20

no_index:
  directory:
    - t
    - examples

resources:
  license:    http://dev.perl.org/licenses/
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=CPAN-Testers-Data-Uploads
  repository: http://github.com/barbie/cpan-testers-data-uploads
meta-spec:
   version:   1.4
   url:       http://module-build.sourceforge.net/META-spec-v1.4.html
generated_by: Hand 1.0
