--- #YAML:1.0
name:                     CPAN-Testers-Data-Uploads
version:                  0.11
abstract:                 CPAN Testers Uploads Database Generator
author:
  - Barbie <barbie@cpan.org>

license:                  perl
distribution_type:        module
installdirs:              site

requires:
  Class::Accessor::Fast:            0
  CPAN::DistnameInfo:               0
  CPAN::Testers::Common::Article:   0
  CPAN::Testers::Common::DBUtils:   0
  Config::IniFiles:                 0
  DBD::mysql:                       0
  DBD::SQLite:                      0
  File::Basename:                   0
  File::Find::Rule:                 0
  File::Path:                       0
  File::Slurp:                      0
  Getopt::Long:                     0
  IO::File:                         0
  Net::NNTP:                        0
recommends:
  Test::More:                       0.70
  Test::Pod:                        1.00
  Test::Pod::Coverage:              0.08
  Test::CPAN::Meta:                 0.12
build_requires:
  Test::More:                       0.01
  Archive::Extract:                 0

provides:
  CPAN::Testers::Data::Uploads:
    file:     lib/CPAN/Testers/Data/Uploads.pm
    version:  0.11

no_index:
  directory:
    - t
    - examples

resources:
  license:    http://dev.perl.org/licenses/
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=CPAN-Testers-Data-Generator

meta-spec:
   version:   1.4
   url:       http://module-build.sourceforge.net/META-spec-v1.4.html
generated_by: Hand 1.0
